-- +goose NO TRANSACTION
-- +goose Up
-- this is generated by a script
SELECT add_data_node('dn2', host => 'pg_data_node_2', port => 5432, database => 'vulcanize_testing_v4', password => 'password');
-- SELECT attach_data_node('dn2', 'eth.log_cids', if_not_attached => true);
-- SELECT attach_data_node('dn2', 'eth.access_list_elements', if_not_attached => true);
-- SELECT attach_data_node('dn2', 'eth.state_accounts', if_not_attached => true);
-- SELECT attach_data_node('dn2', 'eth.storage_cids', if_not_attached => true);
-- SELECT attach_data_node('dn2', 'eth.state_cid', if_not_attached => true);
-- SELECT attach_data_node('dn2', 'eth.receipt_cids', if_not_attached => true);
-- SELECT attach_data_node('dn2', 'eth.transaction_cids', if_not_attached => true);
-- SELECT attach_data_node('dn2', 'eth.uncle_cids', if_not_attached => true);
-- SELECT attach_data_node('dn2', 'eth.header_cid', if_not_attached => true);
-- SELECT attach_data_node('dn2', 'public.blocks', if_not_attached => true);
SELECT add_data_node('dn1', host => 'pg_data_node_1', port => 5432, database => 'vulcanize_testing_v4', password => 'password');
-- SELECT attach_data_node('dn1', 'eth.log_cids', if_not_attached => true);
-- SELECT attach_data_node('dn1', 'eth.access_list_elements', if_not_attached => true);
-- SELECT attach_data_node('dn1', 'eth.state_accounts', if_not_attached => true);
-- SELECT attach_data_node('dn1', 'eth.storage_cids', if_not_attached => true);
-- SELECT attach_data_node('dn1', 'eth.state_cid', if_not_attached => true);
-- SELECT attach_data_node('dn1', 'eth.receipt_cids', if_not_attached => true);
-- SELECT attach_data_node('dn1', 'eth.transaction_cids', if_not_attached => true);
-- SELECT attach_data_node('dn1', 'eth.uncle_cids', if_not_attached => true);
-- SELECT attach_data_node('dn1', 'eth.header_cid', if_not_attached => true);
-- SELECT attach_data_node('dn1', 'public.blocks', if_not_attached => true);
CALL distributed_exec($$ CREATE SCHEMA eth $$);

-- +goose Down
-- this is generated by a script
CALL distributed_exec($$ DROP SCHEMA eth $$);
-- SELECT detach_data_node('dn1', force => true, if_attached = true);
SELECT delete_data_node('dn1', force => true, if_attached => true);
-- SELECT detach_data_node('dn2', force => true, if_attached = true);
SELECT delete_data_node('dn2', force => true, if_attached => true);
