name: Basic test
on: [pull_request]

jobs:
  basic-test:
    name: Build and sanity check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: docker compose build
      - name: Run Docker containers
        run: docker compose up -d
      - name: Check migration version
        timeout-minutes: 1
        run: |
          while
            version=$(docker compose run --rm migrations version 2>&1 | tail -1 | awk '{print $(NF)}')
            [[ $version != 21 ]]; do
            echo "Incorrect version: $version"
            echo "Retrying..."
          done
